version: '3.8'

services:
  plant-disease-app:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./Flask\ Deployed\ App:/app
    environment:
      - PYTHONUNBUFFERED=1
