version: '3.8'
services:
  web:
    build:
      context: ./Flask Deployed App
    ports:
      - "5000:5000"
    volumes:
      - ./Flask Deployed App:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn app:app
